apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort # 1. Automatically opens a static port on your cluster nodes
  selector:
    app: webapp # 2. Routes traffic directly to your NGINX Pod. This should match the pod's label.
  ports:
  - port: 80 # The port inside the cluster
    targetPort: 80 # The port NGINX listens on
    nodePort: 32000 # The static port you can access from your local machine
